replicaCount: 3

image:
  tag: latest

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  path: /

nginx-ingress:
  rbac:
    create: true
